#!/bin/sh
echo 288 > /sys/class/gpio/export
echo 289 > /sys/class/gpio/export
echo 290 > /sys/class/gpio/export
echo 291 > /sys/class/gpio/export
echo 292 > /sys/class/gpio/export
echo 293 > /sys/class/gpio/export
echo 294 > /sys/class/gpio/export
echo 295 > /sys/class/gpio/export
echo 296 > /sys/class/gpio/export
echo 297 > /sys/class/gpio/export
echo 298 > /sys/class/gpio/export
echo 299 > /sys/class/gpio/export
echo 300 > /sys/class/gpio/export
echo 301 > /sys/class/gpio/export
echo 302 > /sys/class/gpio/export
echo 303 > /sys/class/gpio/export
echo 304 > /sys/class/gpio/export
echo 305 > /sys/class/gpio/export
echo 306 > /sys/class/gpio/export
echo 307 > /sys/class/gpio/export
echo 308 > /sys/class/gpio/export
echo 309 > /sys/class/gpio/export
echo 310 > /sys/class/gpio/export
echo 311 > /sys/class/gpio/export
echo 312 > /sys/class/gpio/export
echo 313 > /sys/class/gpio/export
echo 314 > /sys/class/gpio/export
echo 315 > /sys/class/gpio/export
echo 316 > /sys/class/gpio/export
echo 317 > /sys/class/gpio/export
echo 318 > /sys/class/gpio/export
echo 319 > /sys/class/gpio/export
echo 320 > /sys/class/gpio/export
echo 321 > /sys/class/gpio/export
echo 322 > /sys/class/gpio/export
echo 323 > /sys/class/gpio/export
echo 324 > /sys/class/gpio/export
echo 325 > /sys/class/gpio/export
echo 326 > /sys/class/gpio/export
echo 327 > /sys/class/gpio/export
echo 328 > /sys/class/gpio/export
echo 329 > /sys/class/gpio/export
echo 330 > /sys/class/gpio/export
echo 331 > /sys/class/gpio/export
echo 332 > /sys/class/gpio/export
echo 333 > /sys/class/gpio/export
echo 334 > /sys/class/gpio/export
echo 335 > /sys/class/gpio/export
echo 336 > /sys/class/gpio/export
echo 337 > /sys/class/gpio/export
echo 338 > /sys/class/gpio/export
echo 339 > /sys/class/gpio/export
echo 340 > /sys/class/gpio/export
echo 341 > /sys/class/gpio/export
echo 342 > /sys/class/gpio/export
echo 343 > /sys/class/gpio/export
echo 344 > /sys/class/gpio/export
echo 345 > /sys/class/gpio/export
echo 346 > /sys/class/gpio/export
echo 347 > /sys/class/gpio/export
echo 348 > /sys/class/gpio/export
echo 349 > /sys/class/gpio/export
echo 350 > /sys/class/gpio/export
echo 351 > /sys/class/gpio/export
echo 352 > /sys/class/gpio/export
echo 353 > /sys/class/gpio/export
echo 354 > /sys/class/gpio/export
echo 355 > /sys/class/gpio/export
echo 356 > /sys/class/gpio/export
echo 357 > /sys/class/gpio/export
echo 358 > /sys/class/gpio/export
echo 359 > /sys/class/gpio/export
echo 360 > /sys/class/gpio/export
echo 361 > /sys/class/gpio/export
echo 362 > /sys/class/gpio/export
echo 363 > /sys/class/gpio/export
echo 364 > /sys/class/gpio/export
echo 365 > /sys/class/gpio/export
echo 366 > /sys/class/gpio/export
echo 367 > /sys/class/gpio/export
